#pragma once

#include <winioctl.h>

#define DUALDESK_IOCTL_BASE 0x800

// IOCTL codes
#define IOCTL_DUALDESK_GET_DEVICES \
    CTL_CODE(DUALDESK_IOCTL_BASE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DUALDESK_ASSIGN_DEVICE \
    CTL_CODE(DUALDESK_IOCTL_BASE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DUALDESK_ROUTE_INPUT \
    CTL_CODE(DUALDESK_IOCTL_BASE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DUALDESK_LOCK_CURSOR \
    CTL_CODE(DUALDESK_IOCTL_BASE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Data structures
typedef struct _DUALDESK_DEVICE_INFO {
    ULONG DeviceId;
    ULONG DeviceType;  // 0=Keyboard, 1=Mouse
    ULONG WorkspaceId;
    ULONG MonitorIndex;
} DUALDESK_DEVICE_INFO, *PDUALDESK_DEVICE_INFO;

typedef struct _DUALDESK_ROUTE_INFO {
    ULONG DeviceId;
    ULONG WorkspaceId;
    ULONG WindowHandle;
    BOOLEAN IsKeyboard;
} DUALDESK_ROUTE_INFO, *PDUALDESK_ROUTE_INFO;

typedef struct _DUALDESK_LOCK_INFO {
    ULONG MonitorIndex;
    BOOLEAN LockCursor;
} DUALDESK_LOCK_INFO, *PDUALDESK_LOCK_INFO;