#pragma once

#ifndef IOCTL_CODES_H
#define IOCTL_CODES_H

#include <windows.h>

// IOCTL Codes for DualDesk driver
#define IOCTL_GET_DRIVER_STATUS    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ROUTE_INPUT          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_LOCK_WINDOW          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CONFINE_MOUSE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_MONITOR_BOUNDS   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_MONITOR_BOUNDS   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Driver status structure
typedef struct _DRIVER_STATUS {
    BOOLEAN IsRunning;
    BOOLEAN IsIsolatingInput;
    ULONG ActiveMonitors;
    ULONG ConnectedKeyboards;
    ULONG ConnectedMice;
} DRIVER_STATUS, *PDRIVER_STATUS;

// Monitor bounds structure
typedef struct _MONITOR_BOUNDS {
    ULONG MonitorId;
    LONG Left;
    LONG Top;
    LONG Right;
    LONG Bottom;
} MONITOR_BOUNDS, *PMONITOR_BOUNDS;

// Input route structure
typedef struct _INPUT_ROUTE {
    ULONG DeviceId;
    ULONG MonitorId;
    BOOLEAN IsKeyboard;
    BOOLEAN IsMouse;
} INPUT_ROUTE, *PINPUT_ROUTE;

#endif // IOCTL_CODES_H